server:
  port: 8443
queue:
  entregas: boaentrega-entregas
  entregasDlq: boaentrega-entregas-dlq
  faturamento: boaentrega-faturamento
  faturamentoDlq: boaentrega-faturamento-dlq
webhook:
  url: http://localhost:8084/c8cc3160-375f-4874-997c-72502f6523c5
  apiKey: sk_test_2eef1ca4-75af-42f3-a8d4-e83da8090ff9
aws:
  dynamoDB:
    endpoint: http://localhost:4566
    accessKey: teste
    secretKey: teste
  region: sa-east-1
